<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerMqstvus\appProdProjectContainer::class, false)) {
    require __DIR__.'/ContainerMqstvus/appProdProjectContainer.php';
}

if (!class_exists(appProdProjectContainer::class, false)) {
    class_alias(\ContainerMqstvus\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMqstvus\appProdProjectContainer();
