<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerOnu1lf5\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerOnu1lf5/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerOnu1lf5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOnu1lf5\appDevDebugProjectContainer();
